### ISSUE TITLE
Can not copy code blocks from documentation page.

### ISSUE THREAD

**Issue by jschiarizzi** [uport-project/docs#30]
I can't easily highlight code blocks in order to copy/paste from docs, due to styling. 

Reproduced in chrome and firefox here https://developer.uport.me/gettingstarted

**Comment by KamesCG** [comment]
@localredhead Thoughts on changing the `::selection` on `code` elements, so it's easier to identify what is being copied and pasted?

**Comment by localredhead** [comment]
Hello @jschiarizzi - Version 2.3.0 of the developer site has been deployed which addresses this.  

https://github.com/uport-project/uport-project.github.io/commit/67e49ba3bee51e80132cf4788368a3f6108058e6
