### ISSUE TITLE
Go through the Request Credentials guides and update for major release changes 

### ISSUE THREAD

**Issue by localredhead** [uport-project/docs#38]
Please base your branch and PR from this `feature/did-major-release`

- [ ] update request credentials for the proper amount of detail, omitting unecessary inclusion of chasqui, etc.
- [ ] remove or replace outdated or inaccurate content.  
-  [ ] ‘calling the request method’ should be a link to a guide about transports.   (transports link TBD)
- [ ] the verify credentials section does not need to be added anymore
- [ ] attesting credentials graph is too much detail

**Comment by mi-xu** [comment]
Pages to update:
https://developer.uport.me/requestcredentials
https://developer.uport.me/gettingstarted  
https://developer.uport.me/attestcredentials
https://developer.uport.me/signtransactions
